<?php

namespace Lorisleiva\LaravelSearchString\Visitors;

use Lorisleiva\LaravelSearchString\AST\QuerySymbol;
use Lorisleiva\LaravelSearchString\AST\SoloSymbol;

class IdentifyRelationshipsFromRulesVisitor extends Visitor
{
    public function visitSolo(SoloSymbol $solo)
    {
        return parent::visitSolo($solo); // TODO: Change the autogenerated stub
    }

    public function visitQuery(QuerySymbol $query)
    {
        return parent::visitQuery($query); // TODO: Change the autogenerated stub
    }
}
